### ISSUE TITLE
ImportError: No module named 'google_drive_downloader'

### ISSUE THREAD

**Issue by qingfengmingyue** [S-aiueo32/srntt-pytorch#2]
ImportError: No module named 'google_drive_downloader'

**Comment by S-aiueo32** [comment]
@qingfengmingyue 
Could you confirm it has been installed `googledrivedownloader`?

**Comment by GitHub0830** [comment]
Hello, did you successfully download the pretrained model? @qingfengmingyue

**Comment by Mechazo11** [comment]
Hi @JQJ001 if you are using anaconda with mamba then the following worked for me

```mamba install googledrivedownloader```
