### ISSUE TITLE
Cannot obtain the results with default setting

### ISSUE THREAD

**Issue by CurryYuan** [S-aiueo32/srntt-pytorch#4]
With the default setting, I can only get PSNR around 22 on CUFED5. Do I need additional epoch or change some settings?

**Comment by S-aiueo32** [comment]
@CurryYuan 
In contrast to the paper, I trained the model 100 epochs with 5 epoch pretraining.
Because of [here](https://github.com/ZZUTK/SRNTT/blob/93b9b34011742694b8b04ef570894edd193c03ed/SRNTT/model.py#L292-L293), I selected the numbers as the default of this repo.

**Comment by CurryYuan** [comment]
How did you get the result [here](https://drive.google.com/drive/folders/1ZMmlJD4gHVYUCisRr785h_04zMDyTjC-) ? The performance is promising and close to the paper.

**Comment by S-aiueo32** [comment]
I think you should get the same results without any changes.

Can you reproduce the results along with the following steps?
1. download the completed model from [here](https://drive.google.com/drive/folders/1yrIft2GXcDR-IW_uFLy69caVqEaByFDf?usp=sharing) into `./weights` directory.
1. run the test script on CUFED5
```
python test.py -w ./weights/netG_100.pth --use_weights
```

**Comment by CurryYuan** [comment]
I find that every time I run test.py with the same weights, the results are different. I guess the weights of VGG also need to be loaded.

**Comment by S-aiueo32** [comment]
BTW, could you reproduce the result with the process above? Please report it.

> I find that every time I run test.py with the same weights, the results are different.

In my opinion, `test.py` only contains the deterministic processes so it can't be changed every time.
If you find some randomness of my code, please point it out.

> I guess the weights of VGG also need to be loaded.

Where did it come from? The weights of VGG will be properly loaded from `torchvision.models`.
