### ISSUE TITLE
I think your implementation is a little different from the original implementation.

### ISSUE THREAD

**Issue by later-3** [S-aiueo32/srntt-pytorch#5]
In models/srntt.py line 47: return upscale_plain + base, upscale_srntt + base.
So the neural network learned the (bilinear - upscale_srntt) and (bilinear - upscale_plain)?
Thank you!

**Comment by S-aiueo32** [comment]
@later-3 
As mentioned in the section "Downloading a pre-trained weight", this implementation uses a pre-trained MSRGAN provided by [mmsr](https://github.com/open-mmlab/mmsr). MSRGAN has a long skip-connection forwarding bilinear-upscaled image, so we apply the same residual strategy to the texture-transfer module.

**Comment by later-3** [comment]
@S-aiueo32 
Oh, sorry. I should read the README file carefully. Thank you again.
