### ISSUE TITLE
Why should we add h into the output of self.body(h)?

### ISSUE THREAD

**Issue by HikariS97** [S-aiueo32/srntt-pytorch#6]
Every Resblock has already 'x' added
`    def forward(self, x):
        return self.body(x) + x`

So, why should we to add another 'h' after the output value of the whole resblocks?
`    def forward(self, x):
        h = self.head(x)
        h = self.body(h) + h`

**Comment by S-aiueo32** [comment]
you should read the paper - https://arxiv.org/abs/1609.04802
