### ISSUE TITLE
Question about metrics

### ISSUE THREAD

**Issue by yanx27** [S-aiueo32/srntt-pytorch#7]
Hi, @S-aiueo32 , thank you for your great work. I have a question about why you use rgb_to_grayscale in metric rather than rgb2ycbcr, which is widely use in SR community.

**Comment by S-aiueo32** [comment]
@yanx27 As the best of my knowledge, computing metrics on the Y channel of YCbCr is standard. the Y channel and grayscale are equivalent.

**Comment by yanx27** [comment]
@S-aiueo32 Hi, thank you for your reply. I ran your code and used metrics mentioned above, but obtain 1 PSNR drop compared with metric in [RCAN](https://github.com/yulunzhang/RCAN/blob/a990df18c90cdf2329f519f95543ccb4767edbfe/RCAN_TrainCode/code/utility.py#L133). Is there any different between your codes? I also try matlab PSNR and SSIM, both of them will be higher than results gained by your codes.

**Comment by S-aiueo32** [comment]
Well... do you mean the output images of this project score the higher results on the other projects' metrics?

**Comment by yanx27** [comment]
@S-aiueo32 Yes...

**Comment by yanx27** [comment]
But I don't know why cause it, because I'm not focus on this major ~

**Comment by S-aiueo32** [comment]
I think there are many reasons below:

1. Color transformation
  there are many standards on color transformation like ITU-R BT.601, ITU-R BT.709, etc.
2. Parameter of metrics
  Like SSIM's window size, there are many variants.
3. Value range and data type

Anyway, if you want to compare methods, you must use the same metric for all methods.

**Comment by yanx27** [comment]
@S-aiueo32 I see, thank a lot ~

**Comment by S-aiueo32** [comment]
Good luck bro @yanx27
